apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: muhammadwaqas366/devops-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env: # <--- ADD THIS SECTION
          - name: REACT_APP_BACKEND_URL # This name is common for React apps
            value: "http://backend-service:80" # <-- This is the internal K8s service URL
