apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: muhammadwaqas366/frontend-deployment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # <--- CHANGE THIS TO 80 (Nginx port)
