apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: devops-k8s
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true" # <--- ADD THIS ANNOTATION
spec:
  ingressClassName: nginx
  rules:
    - host: devops.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific # <--- CHANGE THIS FROM Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /(.*)
            pathType: ImplementationSpecific # <--- CHANGE THIS FROM Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
